language: minimal
dist: xenial
services:
  - docker

before_install:
  - curl https://raw.githubusercontent.com/plicease/cip/master/bin/travis-bootstrap | bash
  - cip before-install

install:
  - cip diag
  - cip install

script:
  - cip script

jobs:
  include:
    - env: CIP_TAG=5.29 CIP_ENV=ALIEN_INSTALL_TYPE=share
    - env: CIP_TAG=5.29 CIP_ENV=ALIEN_INSTALL_TYPE=system
    - env: CIP_TAG=5.28 CIP_ENV=ALIEN_INSTALL_TYPE=share
    - env: CIP_TAG=5.28 CIP_ENV=ALIEN_INSTALL_TYPE=system

cache:
  directories:
    - "$HOME/.cip"
